services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
